workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 30
    environment:
      node: 18
      npm_cache: true
    cache:
      cache_paths:
        - ManifestApp/node_modules
    scripts:
      - name: Install dependencies
        script: |
          cd ManifestApp
          npm install
      - name: Build iOS with EAS
        script: |
          cd ManifestApp
          npx eas-cli@latest build --platform ios --profile ios-beta --non-interactive
    artifacts:
      - ManifestApp/build/**/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true