workflows:
  react-native-ios-simple:
    name: React Native iOS (Simple NPX)
    max_build_duration: 40
    environment:
      groups:
        - expo_credentials  # EXPO_TOKEN here
      node: 18
    scripts:
      - name: Environment Check
        script: |
          echo "=== Environment Check ==="
          echo "Node: $(node --version)"
          echo "NPM: $(npm --version)"
          
          if [ -z "$EXPO_TOKEN" ]; then
            echo "❌ EXPO_TOKEN not found"
            exit 1
          fi
          echo "✅ EXPO_TOKEN is set (${#EXPO_TOKEN} chars)"
          
      - name: Install Dependencies
        script: |
          cd ManifestApp
          echo "=== Installing Dependencies ==="
          npm ci
          
      - name: Direct NPX Build
        script: |
          cd ManifestApp
          echo "=== Direct NPX EAS Build ==="
          
          # Export token
          export EXPO_TOKEN="$EXPO_TOKEN"
          
          # Build directly with npx (no global install needed)
          npx eas-cli@latest build \
            --platform ios \
            --profile ios-beta \
            --non-interactive
            
    artifacts:
      - ManifestApp/**/*.ipa