workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 30
    environment:
      node: 18
    integrations:
      app_store_connect: APPLE_ID_INTEGRATION
    scripts:
      - name: Install npm dependencies
        script: |
          cd ManifestApp
          npm install
      - name: Build iOS
        script: |
          cd ManifestApp
          npx eas-cli@latest build --platform ios --profile ios-beta --non-interactive
    artifacts:
      - ManifestApp/build/**/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true